package com.dyg.benimkuaforum.util.homeslider

import com.dyg.benimkuaforum.R

val circularIcons = arrayOf(
    R.drawable.circular1,
    R.drawable.circular2,
    R.drawable.circular3,
    R.drawable.circular4,
    R.drawable.circular5,
    R.drawable.circular6,
    R.drawable.circular7,
    R.drawable.circular8,
    R.drawable.circular9,
    R.drawable.circular10,
    R.drawable.circular11,
    R.drawable.circular12,
    R.drawable.circular13,
    R.drawable.circular14,
    R.drawable.circular15,
    R.drawable.circular16,
    R.drawable.circular17,
    R.drawable.circular18,
    R.drawable.circular19,
    R.drawable.circular20,
    R.drawable.circular21,
    R.drawable.circular22,
    R.drawable.circular23,
    R.drawable.circular24,
    R.drawable.circular25,
    R.drawable.circular26,
    R.drawable.circular27,
    R.drawable.circular28,
    R.drawable.circular29,
    R.drawable.circular30,
    R.drawable.circular31,
    R.drawable.circular32,
    R.drawable.circular33,
    R.drawable.circular34,
    R.drawable.circular35,
    R.drawable.circular36,
    R.drawable.circular37,
    R.drawable.circular38,
    R.drawable.circular39,
    R.drawable.circular40
)